# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0010_auto_20171226_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='application_link',
            field=models.CharField(default=b'/', max_length=500),
        ),
    ]
