# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('jobpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='owned_by_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
