# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.CharField(default=b'sfsdf', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='experience',
            field=models.CharField(default=b'sfsdf', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='hours',
            field=models.CharField(default=b'sfsdf', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='salary',
            field=models.CharField(default=b'sfsdf', max_length=200),
        ),
    ]
