# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0002_post_owned_by_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='owned_by_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comp', related_query_name='comps', to='company.Company'),
        ),
    ]
