# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0002_auto_20171226_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='duration',
            field=models.CharField(choices=[(b'FT', b'Fulltime'), (b'PT', b'Partime')], default=b'FT', max_length=2),
        ),
    ]
