# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0005_auto_20171226_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='duration',
            field=models.CharField(choices=[(b'FT', b'Full-time'), (b'PT', b'Part-time')], default=b'PMT', max_length=4),
        ),
    ]
