# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0007_auto_20171226_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='duration',
            field=models.CharField(choices=[(b'Full-time', b'Full-time'), (b'Part-time', b'Part-time')], default=b'PMT', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='experience',
            field=models.CharField(choices=[(b'Intern', b'Intern'), (b'Junior', b'Junior'), (b'Mid-Level', b'Mid'), (b'Senior', b'Senior')], default=b'Intern', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='hours',
            field=models.CharField(choices=[(b'PMT', b'Permanent'), (b'CNT', b'Contract')], default=b'Full-time', max_length=20),
        ),
    ]
