# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0013_auto_20171230_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.CharField(choices=[(b'Engineering', b'Engineering'), (b'Customer', b'Customer'), (b'Product', b'Product'), (b'Marketing', b'Marketing'), (b'Sales', b'Sales'), (b'Operations', b'Operations')], default=b'Engineering', max_length=20),
        ),
    ]
