# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=1, upload_to='user_single_images/'),
        ),
    ]
