# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20171226_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default='Enter company description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='Enter company name', max_length=200),
        ),
    ]
