# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20171226_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(default='/', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='large_logo',
            field=models.ImageField(blank=True, default='website_defaults/logo_large_default.png', upload_to='user_single_images/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='small_logo',
            field=models.ImageField(blank=True, default='website_defaults/logo_small_default.png', upload_to='user_single_images/'),
        ),
    ]
