# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='content',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='location',
        ),
    ]
