# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20171201_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='content',
            field=models.TextField(default='test'),
        ),
    ]
