# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=models.TextField(default='resume content'),
        ),
    ]
