# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20171203_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='title',
        ),
    ]
