# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_remove_resume_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='testtest', max_length=200),
        ),
    ]
