# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 23:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0006_resume_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='image name', max_length=200)),
                ('image', models.ImageField(default=1, upload_to='user_single_images/')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='title',
        ),
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=models.TextField(default='Default resume content'),
        ),
        migrations.AddField(
            model_name='singleimage',
            name='parentCV',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
    ]
