# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20171209_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleimage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='singleimage',
            name='path',
        ),
        migrations.AddField(
            model_name='singleimage',
            name='image_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
