# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20171210_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleimage',
            name='name',
            field=models.CharField(default='sample name', max_length=200),
        ),
    ]
