# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_singleimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleimage',
            name='image_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
