# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20171210_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singleimage',
            old_name='ownerOwner',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='singleimage',
            name='image',
        ),
    ]
