# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_remove_singleimage_parentcv'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleimage',
            name='parentCV',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
    ]
