# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_singleimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleimage',
            name='image',
            field=models.FileField(default=1, upload_to='user_single_images/'),
        ),
    ]
