# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_auto_20171211_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='share_url',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
