# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_slideshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleimage',
            name='parentSlideShow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.SlideShow'),
        ),
    ]
