# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_singleimage_parentslideshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleimage',
            name='path',
            field=models.CharField(default='somepath', max_length=300),
        ),
        migrations.AddField(
            model_name='singleimage',
            name='url',
            field=models.CharField(default='someurl', max_length=300),
        ),
    ]
