# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_auto_20171221_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleimage',
            name='path',
        ),
        migrations.RemoveField(
            model_name='singleimage',
            name='url',
        ),
    ]
